unit TestUSettings;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, USettings;

type
  // Test methods for class TSettings

  TestTSettings = class(TTestCase)
  strict private
    FSettings: TSettings;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestloadSettings;
    procedure Testsave;
  end;

implementation

procedure TestTSettings.SetUp;
begin
  FSettings := TSettings.Create;
end;

procedure TestTSettings.TearDown;
begin
  FSettings.Free;
  FSettings := nil;
end;

procedure TestTSettings.TestloadSettings;
var
  pFilePath: string;
begin
  // TODO: Setup method call parameters
  FSettings.loadSettings(pFilePath);
  // TODO: Validate method results
end;

procedure TestTSettings.Testsave;
begin
  FSettings.save;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSettings.Suite);
end.

