unit TestUAppUtils;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UAppUtils;

type
  // Test methods for class TAppUtils

  TestTAppUtils = class(TTestCase)
  strict private
    FAppUtils: TAppUtils;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetApplicationName;
    procedure TestGetVersaoArq;
  end;

implementation

procedure TestTAppUtils.SetUp;
begin
  FAppUtils := TAppUtils.Create;
end;

procedure TestTAppUtils.TearDown;
begin
  FAppUtils.Free;
  FAppUtils := nil;
end;

procedure TestTAppUtils.TestGetApplicationName;
begin
  CheckEquals('TimeBox',GetApplicationName);
end;

procedure TestTAppUtils.TestGetVersaoArq;
begin
   CheckEquals('1.0.0.0', GetVersaoArq);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTAppUtils.Suite);
end.

